spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false
    date-format: "yyyy-MM-dd HH:mm"
  flyway:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: none
#      ddl-auto: drop-and-create
    generate-ddl: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  datasource:
        url: jdbc:h2:file:~/egz

  h2:
    console.enabled: true


logging:
  level:
    lt:
      techin: DEBUG
    org:
      springframework: INFO

      hibernate:
        SQL: DEBUG
        type: TRACE
      type:
        descriptor:
          sql:
            BasicBinder: DEBUG


